# ---------------------------------------------------------------------------
# Secret Manager — mTLS certificates and DB password
#
# Secrets are generated by Terraform on first apply.  Controller and agent
# VMs pull the appropriate secrets at startup using the instance's service
# account (workload identity).
#
# Secret layout:
#   encodeswarmr-<env>-ca-cert          — CA certificate (PEM)
#   encodeswarmr-<env>-ca-key           — CA private key  (PEM, controller-only access)
#   encodeswarmr-<env>-controller-cert  — Controller TLS certificate (PEM)
#   encodeswarmr-<env>-controller-key   — Controller TLS private key  (PEM)
#   encodeswarmr-<env>-agent-cert       — Agent TLS certificate (PEM)
#   encodeswarmr-<env>-agent-key        — Agent TLS private key  (PEM)
#   encodeswarmr-<env>-db-password      — PostgreSQL password
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Generate mTLS certificates with Terraform TLS provider.
# In production, replace with certificates issued by your internal CA or
# a managed PKI service.
# ---------------------------------------------------------------------------

resource "tls_private_key" "ca" {
  algorithm = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem   = tls_private_key.ca.private_key_pem
  is_ca_certificate = true

  subject {
    common_name  = "encodeswarmr CA (${var.environment})"
    organization = "encodeswarmr"
  }

  validity_period_hours = 87600 # 10 years
  early_renewal_hours   = 720   # 30 days

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "cert_signing",
    "crl_signing",
  ]
}

resource "tls_private_key" "controller" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_cert_request" "controller" {
  private_key_pem = tls_private_key.controller.private_key_pem

  subject {
    common_name  = "controller.encodeswarmr.internal"
    organization = "encodeswarmr"
  }

  dns_names = ["controller.encodeswarmr.internal", "localhost"]
}

resource "tls_locally_signed_cert" "controller" {
  cert_request_pem   = tls_cert_request.controller.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 26280 # 3 years
  early_renewal_hours   = 720

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
    "client_auth",
  ]
}

resource "tls_private_key" "agent" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P384"
}

resource "tls_cert_request" "agent" {
  private_key_pem = tls_private_key.agent.private_key_pem

  subject {
    common_name  = "agent.encodeswarmr.internal"
    organization = "encodeswarmr"
  }
}

resource "tls_locally_signed_cert" "agent" {
  cert_request_pem   = tls_cert_request.agent.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 26280
  early_renewal_hours   = 720

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "client_auth",
  ]
}

# ---------------------------------------------------------------------------
# Secret Manager resources
# ---------------------------------------------------------------------------

locals {
  secrets = {
    ca-cert         = tls_self_signed_cert.ca.cert_pem
    ca-key          = tls_private_key.ca.private_key_pem
    controller-cert = tls_locally_signed_cert.controller.cert_pem
    controller-key  = tls_private_key.controller.private_key_pem
    agent-cert      = tls_locally_signed_cert.agent.cert_pem
    agent-key       = tls_private_key.agent.private_key_pem
    db-password     = var.db_password
  }
}

resource "google_secret_manager_secret" "secrets" {
  for_each  = local.secrets
  secret_id = "${local.name_prefix}-${each.key}"
  project   = var.project_id

  labels = local.common_labels

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "secrets" {
  for_each    = local.secrets
  secret      = google_secret_manager_secret.secrets[each.key].id
  secret_data = each.value
}

# ---------------------------------------------------------------------------
# IAM: Controller service account can read controller certs + CA cert.
# ---------------------------------------------------------------------------

resource "google_secret_manager_secret_iam_member" "controller_reads" {
  for_each = toset(["ca-cert", "controller-cert", "controller-key", "db-password"])

  secret_id = google_secret_manager_secret.secrets[each.key].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.controller.email}"
}

# ---------------------------------------------------------------------------
# IAM: Agent service account can read agent certs + CA cert.
# ---------------------------------------------------------------------------

resource "google_secret_manager_secret_iam_member" "agent_reads" {
  for_each = toset(["ca-cert", "agent-cert", "agent-key"])

  secret_id = google_secret_manager_secret.secrets[each.key].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.agent.email}"
}
