{{- if and .Values.hpa.enabled (ne .Values.agent.kind "DaemonSet") -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "encodeswarmr.fullname" . }}-agent
  labels:
    {{- include "encodeswarmr.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "encodeswarmr.fullname" . }}-agent
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
{{- end }}
