apiVersion: v1
kind: Secret
metadata:
  name: {{ include "encodeswarmr.fullname" . }}-secrets
  labels:
    {{- include "encodeswarmr.labels" . | nindent 4 }}
type: Opaque
stringData:
  ENCODESWARMR_DB_URL: {{ .Values.postgres.dsn | quote }}
  ENCODESWARMR_SESSION_SECRET: {{ .Values.auth.sessionSecret | quote }}
{{- if .Values.tls.caCert }}
data:
  tls-ca.pem: {{ .Values.tls.caCert }}
  tls-cert.pem: {{ .Values.tls.cert }}
  tls-key.pem: {{ .Values.tls.key }}
{{- end }}
