apiVersion: v1
kind: Service
metadata:
  name: {{ include "encodeswarmr.fullname" . }}-controller
  labels:
    {{- include "encodeswarmr.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.controller.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "encodeswarmr.controllerSelectorLabels" . | nindent 4 }}
