// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/encoder/v1/agent.proto

package encoderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentState int32

const (
	AgentState_AGENT_STATE_UNSPECIFIED AgentState = 0
	AgentState_AGENT_STATE_IDLE        AgentState = 1
	AgentState_AGENT_STATE_BUSY        AgentState = 2
	AgentState_AGENT_STATE_DRAINING    AgentState = 3
	AgentState_AGENT_STATE_OFFLINE     AgentState = 4
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "AGENT_STATE_IDLE",
		2: "AGENT_STATE_BUSY",
		3: "AGENT_STATE_DRAINING",
		4: "AGENT_STATE_OFFLINE",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED": 0,
		"AGENT_STATE_IDLE":        1,
		"AGENT_STATE_BUSY":        2,
		"AGENT_STATE_DRAINING":    3,
		"AGENT_STATE_OFFLINE":     4,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_encoder_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_proto_encoder_v1_agent_proto_enumTypes[0]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AgentInfo struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Hostname     string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddress    string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	AgentVersion string                 `protobuf:"bytes,3,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Tags         []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Gpu          *GPUCapabilities       `protobuf:"bytes,5,opt,name=gpu,proto3" json:"gpu,omitempty"`
	// OS info (e.g. "Windows Server 2022 Build 20348")
	OsVersion string `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	// Logical CPU count
	CpuCount int32 `protobuf:"varint,7,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	// Total physical RAM in MiB
	RamMib        int64 `protobuf:"varint,8,opt,name=ram_mib,json=ramMib,proto3" json:"ram_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AgentInfo) GetGpu() *GPUCapabilities {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *AgentInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *AgentInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *AgentInfo) GetRamMib() int64 {
	if x != nil {
		return x.RamMib
	}
	return 0
}

type GPUCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"` // "nvidia", "intel", "amd"
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`   // e.g. "RTX 4090"
	Nvenc         bool                   `protobuf:"varint,3,opt,name=nvenc,proto3" json:"nvenc,omitempty"`
	Qsv           bool                   `protobuf:"varint,4,opt,name=qsv,proto3" json:"qsv,omitempty"`
	Amf           bool                   `protobuf:"varint,5,opt,name=amf,proto3" json:"amf,omitempty"`
	VramMb        int32                  `protobuf:"varint,6,opt,name=vram_mb,json=vramMb,proto3" json:"vram_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUCapabilities) Reset() {
	*x = GPUCapabilities{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUCapabilities) ProtoMessage() {}

func (x *GPUCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUCapabilities.ProtoReflect.Descriptor instead.
func (*GPUCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GPUCapabilities) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GPUCapabilities) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GPUCapabilities) GetNvenc() bool {
	if x != nil {
		return x.Nvenc
	}
	return false
}

func (x *GPUCapabilities) GetQsv() bool {
	if x != nil {
		return x.Qsv
	}
	return false
}

func (x *GPUCapabilities) GetAmf() bool {
	if x != nil {
		return x.Amf
	}
	return false
}

func (x *GPUCapabilities) GetVramMb() int32 {
	if x != nil {
		return x.VramMb
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // UUID assigned / confirmed by controller
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                // Human-readable, e.g. "pending approval"
	Approved      bool                   `protobuf:"varint,4,opt,name=approved,proto3" json:"approved,omitempty"`             // false → agent should wait and re-register
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

type HeartbeatReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current agent state as reported by the agent itself.
	State AgentState `protobuf:"varint,2,opt,name=state,proto3,enum=encoder.v1.AgentState" json:"state,omitempty"`
	// Optional metrics snapshot.
	Metrics *AgentMetrics `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// ID of the task the agent is currently executing (empty if idle).
	CurrentTaskId string `protobuf:"bytes,4,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatReq) Reset() {
	*x = HeartbeatReq{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReq) ProtoMessage() {}

func (x *HeartbeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReq.ProtoReflect.Descriptor instead.
func (*HeartbeatReq) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatReq) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *HeartbeatReq) GetMetrics() *AgentMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HeartbeatReq) GetCurrentTaskId() string {
	if x != nil {
		return x.CurrentTaskId
	}
	return ""
}

type AgentMetrics struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RamPercent float32                `protobuf:"fixed32,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"`
	GpuPercent float32                `protobuf:"fixed32,3,opt,name=gpu_percent,json=gpuPercent,proto3" json:"gpu_percent,omitempty"`
	GpuVramPct float32                `protobuf:"fixed32,4,opt,name=gpu_vram_pct,json=gpuVramPct,proto3" json:"gpu_vram_pct,omitempty"`
	// Disk free on the work/temp directory (MiB).
	DiskFreeMib   int64 `protobuf:"varint,5,opt,name=disk_free_mib,json=diskFreeMib,proto3" json:"disk_free_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMetrics) Reset() {
	*x = AgentMetrics{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMetrics) ProtoMessage() {}

func (x *AgentMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMetrics.ProtoReflect.Descriptor instead.
func (*AgentMetrics) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentMetrics) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *AgentMetrics) GetRamPercent() float32 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *AgentMetrics) GetGpuPercent() float32 {
	if x != nil {
		return x.GpuPercent
	}
	return 0
}

func (x *AgentMetrics) GetGpuVramPct() float32 {
	if x != nil {
		return x.GpuVramPct
	}
	return 0
}

func (x *AgentMetrics) GetDiskFreeMib() int64 {
	if x != nil {
		return x.DiskFreeMib
	}
	return 0
}

type HeartbeatResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true the agent should complete the current task then stop polling.
	Drain bool `protobuf:"varint,1,opt,name=drain,proto3" json:"drain,omitempty"`
	// When true the agent should immediately abort and not pick up new work.
	Disabled bool `protobuf:"varint,2,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Controller time — agents use this for log timestamp alignment only.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResp) Reset() {
	*x = HeartbeatResp{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResp) ProtoMessage() {}

func (x *HeartbeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResp.ProtoReflect.Descriptor instead.
func (*HeartbeatResp) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResp) GetDrain() bool {
	if x != nil {
		return x.Drain
	}
	return false
}

func (x *HeartbeatResp) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *HeartbeatResp) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

type PollTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Gpu           *GPUCapabilities       `protobuf:"bytes,2,opt,name=gpu,proto3" json:"gpu,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskReq) Reset() {
	*x = PollTaskReq{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskReq) ProtoMessage() {}

func (x *PollTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskReq.ProtoReflect.Descriptor instead.
func (*PollTaskReq) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PollTaskReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PollTaskReq) GetGpu() *GPUCapabilities {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *PollTaskReq) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TaskAssignment struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	HasTask    bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	TaskId     string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId      string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ChunkIndex int32                  `protobuf:"varint,4,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// Script files to write to disk (filename → content).
	// Keys are relative paths, e.g. "encode.bat", "source.avs".
	Scripts map[string]string `protobuf:"bytes,5,rep,name=scripts,proto3" json:"scripts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Key-value variables to substitute — supplemental to those embedded in
	// the script content by the template engine.
	Variables map[string]string `protobuf:"bytes,6,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// UNC path to the source file.
	SourcePath string `protobuf:"bytes,7,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// UNC path the agent should write the output to.
	OutputPath string `protobuf:"bytes,8,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	// Hard timeout in seconds.  Agent must abort and report failure if exceeded.
	TimeoutSec int32 `protobuf:"varint,9,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	// Job priority (informational).
	Priority      int32 `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TaskAssignment) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *TaskAssignment) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAssignment) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAssignment) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TaskAssignment) GetScripts() map[string]string {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *TaskAssignment) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *TaskAssignment) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *TaskAssignment) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *TaskAssignment) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskAssignment) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type ProgressUpdate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TaskId      string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId       string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Frame       int64                  `protobuf:"varint,3,opt,name=frame,proto3" json:"frame,omitempty"`
	TotalFrames int64                  `protobuf:"varint,4,opt,name=total_frames,json=totalFrames,proto3" json:"total_frames,omitempty"`
	Fps         float32                `protobuf:"fixed32,5,opt,name=fps,proto3" json:"fps,omitempty"`
	// Estimated seconds remaining.
	EtaSec int32 `protobuf:"varint,6,opt,name=eta_sec,json=etaSec,proto3" json:"eta_sec,omitempty"`
	// Encoding quality metric (e.g. current CRF-adjusted PSNR) — optional.
	Quality       float32                `protobuf:"fixed32,7,opt,name=quality,proto3" json:"quality,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProgressUpdate) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetFrame() int64 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *ProgressUpdate) GetTotalFrames() int64 {
	if x != nil {
		return x.TotalFrames
	}
	return 0
}

func (x *ProgressUpdate) GetFps() float32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *ProgressUpdate) GetEtaSec() int32 {
	if x != nil {
		return x.EtaSec
	}
	return 0
}

func (x *ProgressUpdate) GetQuality() float32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ProgressUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type TaskResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId    string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Success  bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ExitCode int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ErrorMsg string                 `protobuf:"bytes,5,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// Final encoding metrics.
	Metrics     *EncodeMetrics         `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// Set to true when this result was buffered offline and is being replayed.
	OfflineResult bool `protobuf:"varint,9,opt,name=offline_result,json=offlineResult,proto3" json:"offline_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskResult) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *TaskResult) GetMetrics() *EncodeMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TaskResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TaskResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *TaskResult) GetOfflineResult() bool {
	if x != nil {
		return x.OfflineResult
	}
	return false
}

type EncodeMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FramesEncoded int64                  `protobuf:"varint,1,opt,name=frames_encoded,json=framesEncoded,proto3" json:"frames_encoded,omitempty"`
	AvgFps        float32                `protobuf:"fixed32,2,opt,name=avg_fps,json=avgFps,proto3" json:"avg_fps,omitempty"`
	OutputSize    int64                  `protobuf:"varint,3,opt,name=output_size,json=outputSize,proto3" json:"output_size,omitempty"` // bytes
	VmafScore     float32                `protobuf:"fixed32,4,opt,name=vmaf_score,json=vmafScore,proto3" json:"vmaf_score,omitempty"`
	Psnr          float32                `protobuf:"fixed32,5,opt,name=psnr,proto3" json:"psnr,omitempty"`
	Ssim          float32                `protobuf:"fixed32,6,opt,name=ssim,proto3" json:"ssim,omitempty"`
	// Wall-clock encoding duration in seconds.
	DurationSec   int64 `protobuf:"varint,7,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeMetrics) Reset() {
	*x = EncodeMetrics{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeMetrics) ProtoMessage() {}

func (x *EncodeMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeMetrics.ProtoReflect.Descriptor instead.
func (*EncodeMetrics) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *EncodeMetrics) GetFramesEncoded() int64 {
	if x != nil {
		return x.FramesEncoded
	}
	return 0
}

func (x *EncodeMetrics) GetAvgFps() float32 {
	if x != nil {
		return x.AvgFps
	}
	return 0
}

func (x *EncodeMetrics) GetOutputSize() int64 {
	if x != nil {
		return x.OutputSize
	}
	return 0
}

func (x *EncodeMetrics) GetVmafScore() float32 {
	if x != nil {
		return x.VmafScore
	}
	return 0
}

func (x *EncodeMetrics) GetPsnr() float32 {
	if x != nil {
		return x.Psnr
	}
	return 0
}

func (x *EncodeMetrics) GetSsim() float32 {
	if x != nil {
		return x.Ssim
	}
	return 0
}

func (x *EncodeMetrics) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type LogEntry struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId  string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// "stdout", "stderr", or "agent"
	Stream string `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	// "debug", "info", "warn", "error"
	Level     string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Message   string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional structured metadata, e.g. {"frame":2400,"fps":24.5}
	Metadata      *structpb.Struct `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogEntry) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LogEntry) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of results accepted.
	Accepted int32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// IDs of results that were rejected (e.g. already processed).
	RejectedTaskIds []string `protobuf:"bytes,2,rep,name=rejected_task_ids,json=rejectedTaskIds,proto3" json:"rejected_task_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SyncResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *SyncResponse) GetRejectedTaskIds() []string {
	if x != nil {
		return x.RejectedTaskIds
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_encoder_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_encoder_v1_agent_proto protoreflect.FileDescriptor

const file_proto_encoder_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/encoder/v1/agent.proto\x12\n" +
	"encoder.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x83\x02\n" +
	"\tAgentInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12#\n" +
	"\ragent_version\x18\x03 \x01(\tR\fagentVersion\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12-\n" +
	"\x03gpu\x18\x05 \x01(\v2\x1b.encoder.v1.GPUCapabilitiesR\x03gpu\x12\x1d\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tR\tosVersion\x12\x1b\n" +
	"\tcpu_count\x18\a \x01(\x05R\bcpuCount\x12\x17\n" +
	"\aram_mib\x18\b \x01(\x03R\x06ramMib\"\x92\x01\n" +
	"\x0fGPUCapabilities\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05nvenc\x18\x03 \x01(\bR\x05nvenc\x12\x10\n" +
	"\x03qsv\x18\x04 \x01(\bR\x03qsv\x12\x10\n" +
	"\x03amf\x18\x05 \x01(\bR\x03amf\x12\x17\n" +
	"\avram_mb\x18\x06 \x01(\x05R\x06vramMb\"s\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bapproved\x18\x04 \x01(\bR\bapproved\"\xb3\x01\n" +
	"\fHeartbeatReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.encoder.v1.AgentStateR\x05state\x122\n" +
	"\ametrics\x18\x03 \x01(\v2\x18.encoder.v1.AgentMetricsR\ametrics\x12&\n" +
	"\x0fcurrent_task_id\x18\x04 \x01(\tR\rcurrentTaskId\"\xb7\x01\n" +
	"\fAgentMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x02 \x01(\x02R\n" +
	"ramPercent\x12\x1f\n" +
	"\vgpu_percent\x18\x03 \x01(\x02R\n" +
	"gpuPercent\x12 \n" +
	"\fgpu_vram_pct\x18\x04 \x01(\x02R\n" +
	"gpuVramPct\x12\"\n" +
	"\rdisk_free_mib\x18\x05 \x01(\x03R\vdiskFreeMib\"~\n" +
	"\rHeartbeatResp\x12\x14\n" +
	"\x05drain\x18\x01 \x01(\bR\x05drain\x12\x1a\n" +
	"\bdisabled\x18\x02 \x01(\bR\bdisabled\x12;\n" +
	"\vserver_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"k\n" +
	"\vPollTaskReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12-\n" +
	"\x03gpu\x18\x02 \x01(\v2\x1b.encoder.v1.GPUCapabilitiesR\x03gpu\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x81\x04\n" +
	"\x0eTaskAssignment\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vchunk_index\x18\x04 \x01(\x05R\n" +
	"chunkIndex\x12A\n" +
	"\ascripts\x18\x05 \x03(\v2'.encoder.v1.TaskAssignment.ScriptsEntryR\ascripts\x12G\n" +
	"\tvariables\x18\x06 \x03(\v2).encoder.v1.TaskAssignment.VariablesEntryR\tvariables\x12\x1f\n" +
	"\vsource_path\x18\a \x01(\tR\n" +
	"sourcePath\x12\x1f\n" +
	"\voutput_path\x18\b \x01(\tR\n" +
	"outputPath\x12\x1f\n" +
	"\vtimeout_sec\x18\t \x01(\x05R\n" +
	"timeoutSec\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x1a:\n" +
	"\fScriptsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x01\n" +
	"\x0eProgressUpdate\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05frame\x18\x03 \x01(\x03R\x05frame\x12!\n" +
	"\ftotal_frames\x18\x04 \x01(\x03R\vtotalFrames\x12\x10\n" +
	"\x03fps\x18\x05 \x01(\x02R\x03fps\x12\x17\n" +
	"\aeta_sec\x18\x06 \x01(\x05R\x06etaSec\x12\x18\n" +
	"\aquality\x18\a \x01(\x02R\aquality\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe6\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\terror_msg\x18\x05 \x01(\tR\berrorMsg\x123\n" +
	"\ametrics\x18\x06 \x01(\v2\x19.encoder.v1.EncodeMetricsR\ametrics\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12%\n" +
	"\x0eoffline_result\x18\t \x01(\bR\rofflineResult\"\xda\x01\n" +
	"\rEncodeMetrics\x12%\n" +
	"\x0eframes_encoded\x18\x01 \x01(\x03R\rframesEncoded\x12\x17\n" +
	"\aavg_fps\x18\x02 \x01(\x02R\x06avgFps\x12\x1f\n" +
	"\voutput_size\x18\x03 \x01(\x03R\n" +
	"outputSize\x12\x1d\n" +
	"\n" +
	"vmaf_score\x18\x04 \x01(\x02R\tvmafScore\x12\x12\n" +
	"\x04psnr\x18\x05 \x01(\x02R\x04psnr\x12\x12\n" +
	"\x04ssim\x18\x06 \x01(\x02R\x04ssim\x12!\n" +
	"\fduration_sec\x18\a \x01(\x03R\vdurationSec\"\xf1\x01\n" +
	"\bLogEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"V\n" +
	"\fSyncResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12*\n" +
	"\x11rejected_task_ids\x18\x02 \x03(\tR\x0frejectedTaskIds\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\x88\x01\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGENT_STATE_IDLE\x10\x01\x12\x14\n" +
	"\x10AGENT_STATE_BUSY\x10\x02\x12\x18\n" +
	"\x14AGENT_STATE_DRAINING\x10\x03\x12\x17\n" +
	"\x13AGENT_STATE_OFFLINE\x10\x042\xcd\x03\n" +
	"\fAgentService\x12?\n" +
	"\bRegister\x12\x15.encoder.v1.AgentInfo\x1a\x1c.encoder.v1.RegisterResponse\x12@\n" +
	"\tHeartbeat\x12\x18.encoder.v1.HeartbeatReq\x1a\x19.encoder.v1.HeartbeatResp\x12?\n" +
	"\bPollTask\x12\x17.encoder.v1.PollTaskReq\x1a\x1a.encoder.v1.TaskAssignment\x12?\n" +
	"\x0eReportProgress\x12\x1a.encoder.v1.ProgressUpdate\x1a\x0f.encoder.v1.Ack(\x01\x127\n" +
	"\fReportResult\x12\x16.encoder.v1.TaskResult\x1a\x0f.encoder.v1.Ack\x125\n" +
	"\n" +
	"StreamLogs\x12\x14.encoder.v1.LogEntry\x1a\x0f.encoder.v1.Ack(\x01\x12H\n" +
	"\x12SyncOfflineResults\x12\x16.encoder.v1.TaskResult\x1a\x18.encoder.v1.SyncResponse(\x01BCZAgithub.com/badskater/distributed-encoder/internal/proto/encoderv1b\x06proto3"

var (
	file_proto_encoder_v1_agent_proto_rawDescOnce sync.Once
	file_proto_encoder_v1_agent_proto_rawDescData []byte
)

func file_proto_encoder_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_encoder_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_encoder_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_encoder_v1_agent_proto_rawDesc), len(file_proto_encoder_v1_agent_proto_rawDesc)))
	})
	return file_proto_encoder_v1_agent_proto_rawDescData
}

var file_proto_encoder_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_encoder_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_encoder_v1_agent_proto_goTypes = []any{
	(AgentState)(0),               // 0: encoder.v1.AgentState
	(*AgentInfo)(nil),             // 1: encoder.v1.AgentInfo
	(*GPUCapabilities)(nil),       // 2: encoder.v1.GPUCapabilities
	(*RegisterResponse)(nil),      // 3: encoder.v1.RegisterResponse
	(*HeartbeatReq)(nil),          // 4: encoder.v1.HeartbeatReq
	(*AgentMetrics)(nil),          // 5: encoder.v1.AgentMetrics
	(*HeartbeatResp)(nil),         // 6: encoder.v1.HeartbeatResp
	(*PollTaskReq)(nil),           // 7: encoder.v1.PollTaskReq
	(*TaskAssignment)(nil),        // 8: encoder.v1.TaskAssignment
	(*ProgressUpdate)(nil),        // 9: encoder.v1.ProgressUpdate
	(*TaskResult)(nil),            // 10: encoder.v1.TaskResult
	(*EncodeMetrics)(nil),         // 11: encoder.v1.EncodeMetrics
	(*LogEntry)(nil),              // 12: encoder.v1.LogEntry
	(*SyncResponse)(nil),          // 13: encoder.v1.SyncResponse
	(*Ack)(nil),                   // 14: encoder.v1.Ack
	nil,                           // 15: encoder.v1.TaskAssignment.ScriptsEntry
	nil,                           // 16: encoder.v1.TaskAssignment.VariablesEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
}
var file_proto_encoder_v1_agent_proto_depIdxs = []int32{
	2,  // 0: encoder.v1.AgentInfo.gpu:type_name -> encoder.v1.GPUCapabilities
	0,  // 1: encoder.v1.HeartbeatReq.state:type_name -> encoder.v1.AgentState
	5,  // 2: encoder.v1.HeartbeatReq.metrics:type_name -> encoder.v1.AgentMetrics
	17, // 3: encoder.v1.HeartbeatResp.server_time:type_name -> google.protobuf.Timestamp
	2,  // 4: encoder.v1.PollTaskReq.gpu:type_name -> encoder.v1.GPUCapabilities
	15, // 5: encoder.v1.TaskAssignment.scripts:type_name -> encoder.v1.TaskAssignment.ScriptsEntry
	16, // 6: encoder.v1.TaskAssignment.variables:type_name -> encoder.v1.TaskAssignment.VariablesEntry
	17, // 7: encoder.v1.ProgressUpdate.timestamp:type_name -> google.protobuf.Timestamp
	11, // 8: encoder.v1.TaskResult.metrics:type_name -> encoder.v1.EncodeMetrics
	17, // 9: encoder.v1.TaskResult.started_at:type_name -> google.protobuf.Timestamp
	17, // 10: encoder.v1.TaskResult.completed_at:type_name -> google.protobuf.Timestamp
	17, // 11: encoder.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	18, // 12: encoder.v1.LogEntry.metadata:type_name -> google.protobuf.Struct
	1,  // 13: encoder.v1.AgentService.Register:input_type -> encoder.v1.AgentInfo
	4,  // 14: encoder.v1.AgentService.Heartbeat:input_type -> encoder.v1.HeartbeatReq
	7,  // 15: encoder.v1.AgentService.PollTask:input_type -> encoder.v1.PollTaskReq
	9,  // 16: encoder.v1.AgentService.ReportProgress:input_type -> encoder.v1.ProgressUpdate
	10, // 17: encoder.v1.AgentService.ReportResult:input_type -> encoder.v1.TaskResult
	12, // 18: encoder.v1.AgentService.StreamLogs:input_type -> encoder.v1.LogEntry
	10, // 19: encoder.v1.AgentService.SyncOfflineResults:input_type -> encoder.v1.TaskResult
	3,  // 20: encoder.v1.AgentService.Register:output_type -> encoder.v1.RegisterResponse
	6,  // 21: encoder.v1.AgentService.Heartbeat:output_type -> encoder.v1.HeartbeatResp
	8,  // 22: encoder.v1.AgentService.PollTask:output_type -> encoder.v1.TaskAssignment
	14, // 23: encoder.v1.AgentService.ReportProgress:output_type -> encoder.v1.Ack
	14, // 24: encoder.v1.AgentService.ReportResult:output_type -> encoder.v1.Ack
	14, // 25: encoder.v1.AgentService.StreamLogs:output_type -> encoder.v1.Ack
	13, // 26: encoder.v1.AgentService.SyncOfflineResults:output_type -> encoder.v1.SyncResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_encoder_v1_agent_proto_init() }
func file_proto_encoder_v1_agent_proto_init() {
	if File_proto_encoder_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_encoder_v1_agent_proto_rawDesc), len(file_proto_encoder_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_encoder_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_encoder_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_encoder_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_encoder_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_encoder_v1_agent_proto = out.File
	file_proto_encoder_v1_agent_proto_goTypes = nil
	file_proto_encoder_v1_agent_proto_depIdxs = nil
}
