// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/encoder/v1/agent.proto

package encoderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Register_FullMethodName           = "/encoder.v1.AgentService/Register"
	AgentService_Heartbeat_FullMethodName          = "/encoder.v1.AgentService/Heartbeat"
	AgentService_PollTask_FullMethodName           = "/encoder.v1.AgentService/PollTask"
	AgentService_ReportProgress_FullMethodName     = "/encoder.v1.AgentService/ReportProgress"
	AgentService_ReportResult_FullMethodName       = "/encoder.v1.AgentService/ReportResult"
	AgentService_StreamLogs_FullMethodName         = "/encoder.v1.AgentService/StreamLogs"
	AgentService_SyncOfflineResults_FullMethodName = "/encoder.v1.AgentService/SyncOfflineResults"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// AgentService — all RPC calls are initiated by the Windows Agent.
// ---------------------------------------------------------------------------
type AgentServiceClient interface {
	// Called on agent startup to register or re-register with the controller.
	Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Periodic liveness signal (~30 s). Controller replies with any config
	// updates the agent should apply (e.g. drain flag, new allowed_shares).
	Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error)
	// Agent polls for its next task assignment. Returns an empty assignment
	// (has_task = false) when there is nothing to do.
	PollTask(ctx context.Context, in *PollTaskReq, opts ...grpc.CallOption) (*TaskAssignment, error)
	// Agent streams frame-level progress while a task is running.
	ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, Ack], error)
	// Agent reports final result after a task completes or fails.
	ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error)
	// Agent streams stdout/stderr/executor log lines to the controller in
	// real-time. The controller stores them in task_logs and forwards to
	// any active SSE subscribers.
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, Ack], error)
	// After a network outage the agent replays buffered results.
	SyncOfflineResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TaskResult, SyncResponse], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Register(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AgentService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatReq, opts ...grpc.CallOption) (*HeartbeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResp)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PollTask(ctx context.Context, in *PollTaskReq, opts ...grpc.CallOption) (*TaskAssignment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskAssignment)
	err := c.cc.Invoke(ctx, AgentService_PollTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReportProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressUpdate, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportProgressClient = grpc.ClientStreamingClient[ProgressUpdate, Ack]

func (c *agentServiceClient) ReportResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AgentService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsClient = grpc.ClientStreamingClient[LogEntry, Ack]

func (c *agentServiceClient) SyncOfflineResults(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TaskResult, SyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_SyncOfflineResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskResult, SyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SyncOfflineResultsClient = grpc.ClientStreamingClient[TaskResult, SyncResponse]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// AgentService — all RPC calls are initiated by the Windows Agent.
// ---------------------------------------------------------------------------
type AgentServiceServer interface {
	// Called on agent startup to register or re-register with the controller.
	Register(context.Context, *AgentInfo) (*RegisterResponse, error)
	// Periodic liveness signal (~30 s). Controller replies with any config
	// updates the agent should apply (e.g. drain flag, new allowed_shares).
	Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error)
	// Agent polls for its next task assignment. Returns an empty assignment
	// (has_task = false) when there is nothing to do.
	PollTask(context.Context, *PollTaskReq) (*TaskAssignment, error)
	// Agent streams frame-level progress while a task is running.
	ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, Ack]) error
	// Agent reports final result after a task completes or fails.
	ReportResult(context.Context, *TaskResult) (*Ack, error)
	// Agent streams stdout/stderr/executor log lines to the controller in
	// real-time. The controller stores them in task_logs and forwards to
	// any active SSE subscribers.
	StreamLogs(grpc.ClientStreamingServer[LogEntry, Ack]) error
	// After a network outage the agent replays buffered results.
	SyncOfflineResults(grpc.ClientStreamingServer[TaskResult, SyncResponse]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Register(context.Context, *AgentInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatReq) (*HeartbeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) PollTask(context.Context, *PollTaskReq) (*TaskAssignment, error) {
	return nil, status.Error(codes.Unimplemented, "method PollTask not implemented")
}
func (UnimplementedAgentServiceServer) ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedAgentServiceServer) ReportResult(context.Context, *TaskResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedAgentServiceServer) StreamLogs(grpc.ClientStreamingServer[LogEntry, Ack]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) SyncOfflineResults(grpc.ClientStreamingServer[TaskResult, SyncResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncOfflineResults not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Register(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PollTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PollTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PollTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PollTask(ctx, req.(*PollTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).ReportProgress(&grpc.GenericServerStream[ProgressUpdate, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReportProgressServer = grpc.ClientStreamingServer[ProgressUpdate, Ack]

func _AgentService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamLogs(&grpc.GenericServerStream[LogEntry, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsServer = grpc.ClientStreamingServer[LogEntry, Ack]

func _AgentService_SyncOfflineResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SyncOfflineResults(&grpc.GenericServerStream[TaskResult, SyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SyncOfflineResultsServer = grpc.ClientStreamingServer[TaskResult, SyncResponse]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encoder.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AgentService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "PollTask",
			Handler:    _AgentService_PollTask_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _AgentService_ReportResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportProgress",
			Handler:       _AgentService_ReportProgress_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentService_StreamLogs_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncOfflineResults",
			Handler:       _AgentService_SyncOfflineResults_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/encoder/v1/agent.proto",
}
