import type { NodeTemplate, NodeCategory } from '../types/flow'
export type { NodeTemplate } from '../types/flow'

export const NODE_REGISTRY: NodeTemplate[] = [
  // ── Input ──────────────────────────────────────────────────────────────────
  {
    type: 'input_file',
    label: 'Input File',
    category: 'input',
    description: 'Source video file entry point for a single file',
    icon: '📁',
    defaultConfig: { path: '' },
    inputs: 0,
    outputs: 1,
  },
  {
    type: 'input_folder',
    label: 'Input Folder',
    category: 'input',
    description: 'Batch processing — watch a folder for new files',
    icon: '📂',
    defaultConfig: { folder_path: '', file_pattern: '*.mkv' },
    inputs: 0,
    outputs: 1,
  },

  // ── Encoding ───────────────────────────────────────────────────────────────
  {
    type: 'encode_x265',
    label: 'x265 Encode',
    category: 'encoding',
    description: 'Encode with x265 (HEVC). Supports HDR10, DV, and SDR.',
    icon: '🎬',
    defaultConfig: { crf: 18, preset: 'slow', profile: 'main10', tune: '', extra_args: '' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_x264',
    label: 'x264 Encode',
    category: 'encoding',
    description: 'Encode with x264 (H.264). Best compatibility for web delivery.',
    icon: '🎥',
    defaultConfig: { crf: 23, preset: 'medium', profile: 'high', tune: '' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_svtav1',
    label: 'SVT-AV1 Encode',
    category: 'encoding',
    description: 'Encode with SVT-AV1. Excellent efficiency for modern playback.',
    icon: '⚡',
    defaultConfig: { crf: 30, preset: 6 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_ffmpeg_copy',
    label: 'Stream Copy',
    category: 'encoding',
    description: 'Remux streams without re-encoding. Fast and lossless.',
    icon: '📋',
    defaultConfig: { container: 'mkv' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_nvenc',
    label: 'NVENC H.265',
    category: 'encoding',
    description: 'GPU-accelerated HEVC encoding via NVIDIA NVENC.',
    icon: '🚀',
    defaultConfig: { cq: 28, preset: 'p4' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_twopass',
    label: 'Two-Pass Encode',
    category: 'encoding',
    description: 'Two-pass encode targeting a specific bitrate. Pass 1 analyses the source; Pass 2 encodes to the target. Best for consistent file sizes.',
    icon: '🔄',
    defaultConfig: { codec: 'x265', bitrate: 4000, preset: 'slow', profile: 'main10' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_twopass_x264',
    label: 'Two-Pass x264',
    category: 'encoding',
    description: 'Convenience two-pass x264 node. Targets a specific bitrate using the H.264 codec for broad compatibility.',
    icon: '🔄',
    defaultConfig: { bitrate: 6000, preset: 'medium', profile: 'high' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'encode_vmaf_target',
    label: 'VMAF Target Encode',
    category: 'encoding',
    description: 'Iteratively encodes and measures VMAF quality, adjusting CRF via binary search until the target VMAF score is reached.',
    icon: '🎯',
    defaultConfig: {
      target_vmaf: 95,
      codec: 'x265',
      preset: 'slow',
      crf_min: 15,
      crf_max: 28,
      max_iterations: 5,
    },
    inputs: 1,
    outputs: 1,
  },

  // ── Analysis ───────────────────────────────────────────────────────────────
  {
    type: 'analyze_hdr',
    label: 'HDR Detect',
    category: 'analysis',
    description: 'Detect HDR type, Dolby Vision profile, and colour metadata.',
    icon: '🌈',
    defaultConfig: {},
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'analyze_scene',
    label: 'Scene Scan',
    category: 'analysis',
    description: 'Detect scene boundaries for intelligent chunking.',
    icon: '🎞',
    defaultConfig: { threshold: 0.4 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'analyze_vmaf',
    label: 'VMAF Score',
    category: 'analysis',
    description: 'Compute VMAF quality score. Optionally specify a reference path for A/B comparison; defaults to the original source.',
    icon: '📊',
    defaultConfig: { model: 'vmaf_v0.6.1', reference_path: '' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'analyze_probe',
    label: 'Probe Info',
    category: 'analysis',
    description: 'Extract codec, resolution, bitrate, and stream info via ffprobe.',
    icon: '🔍',
    defaultConfig: {},
    inputs: 1,
    outputs: 1,
  },

  // ── Conditions ─────────────────────────────────────────────────────────────
  {
    type: 'cond_file_size',
    label: 'File Size Check',
    category: 'condition',
    description: 'Branch on file size. True output fires when condition is met.',
    icon: '⚖️',
    defaultConfig: { operator: 'gt', size_mb: 1000 },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'cond_resolution',
    label: 'Resolution Check',
    category: 'condition',
    description: 'Branch based on video resolution (width × height).',
    icon: '📐',
    defaultConfig: { min_width: 1920, min_height: 1080 },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'cond_codec',
    label: 'Codec Check',
    category: 'condition',
    description: 'Branch on the source codec (hevc, h264, av1, …).',
    icon: '🔧',
    defaultConfig: { codec: 'hevc' },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'cond_hdr_type',
    label: 'HDR Type Check',
    category: 'condition',
    description: 'Branch on HDR type: HDR10, Dolby Vision, HLG, or SDR.',
    icon: '💡',
    defaultConfig: { hdr_type: 'hdr10' },
    inputs: 1,
    outputs: 2,
  },
  {
    type: 'cond_file_ext',
    label: 'File Extension',
    category: 'condition',
    description: 'Branch based on the file extension.',
    icon: '📝',
    defaultConfig: { extensions: ['.mkv', '.mp4'] },
    inputs: 1,
    outputs: 2,
  },

  // ── Audio ──────────────────────────────────────────────────────────────────
  {
    type: 'audio_flac',
    label: 'Convert to FLAC',
    category: 'audio',
    description: 'Lossless audio conversion to FLAC.',
    icon: '🎵',
    defaultConfig: {},
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'audio_opus',
    label: 'Convert to Opus',
    category: 'audio',
    description: 'Efficient lossy audio encoding with Opus.',
    icon: '🎶',
    defaultConfig: { bitrate: '192k' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'audio_aac',
    label: 'Convert to AAC-LC',
    category: 'audio',
    description: 'AAC-LC audio for broad compatibility.',
    icon: '🔊',
    defaultConfig: { bitrate: '256k' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'audio_extract',
    label: 'Extract Audio',
    category: 'audio',
    description: 'Demux and extract audio tracks from the container.',
    icon: '🎤',
    defaultConfig: { track_index: 0 },
    inputs: 1,
    outputs: 1,
  },

  // ── Subtitles ──────────────────────────────────────────────────────────────
  {
    type: 'subtitle_extract',
    label: 'Extract Subtitles',
    category: 'subtitle',
    description: 'Extract a subtitle track from the container to a standalone file.',
    icon: '💬',
    defaultConfig: { track_index: 0, format: 'srt' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'subtitle_convert',
    label: 'Convert Subtitles',
    category: 'subtitle',
    description: 'Convert a subtitle file from one format to another.',
    icon: '🔄',
    defaultConfig: { input_format: 'srt', output_format: 'ass' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'subtitle_embed',
    label: 'Embed Subtitles',
    category: 'subtitle',
    description: 'Mux a subtitle file into the video container (soft subtitles).',
    icon: '📝',
    defaultConfig: { subtitle_path: '', language: 'eng', default_track: false },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'subtitle_burn',
    label: 'Burn-in Subtitles',
    category: 'subtitle',
    description: 'Burn subtitles permanently into the video frames (hard subtitles).',
    icon: '🔥',
    defaultConfig: { subtitle_path: '', font_size: 24, position: 'bottom' },
    inputs: 1,
    outputs: 1,
  },

  // ── Output ─────────────────────────────────────────────────────────────────
  {
    type: 'output_move',
    label: 'Move File',
    category: 'output',
    description: 'Move the output file to a destination path.',
    icon: '📤',
    defaultConfig: { destination_path: '' },
    inputs: 1,
    outputs: 0,
  },
  {
    type: 'output_copy',
    label: 'Copy File',
    category: 'output',
    description: 'Copy the output file to a destination path.',
    icon: '📑',
    defaultConfig: { destination_path: '' },
    inputs: 1,
    outputs: 0,
  },
  {
    type: 'output_rename',
    label: 'Rename',
    category: 'output',
    description: 'Rename the file using a pattern with variables.',
    icon: '✏️',
    defaultConfig: { pattern: '{{.SOURCE_NAME}}_encoded' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'output_set_path',
    label: 'Set Output Path',
    category: 'output',
    description: 'Override the output path for downstream nodes.',
    icon: '📍',
    defaultConfig: { path: '' },
    inputs: 1,
    outputs: 1,
  },

  // ── Notifications ──────────────────────────────────────────────────────────
  {
    type: 'notify_webhook',
    label: 'Send Webhook',
    category: 'notification',
    description: 'Trigger a configured webhook with a custom message.',
    icon: '🔔',
    defaultConfig: { webhook_id: '', message_template: 'Job completed: {{.SOURCE_NAME}}' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'notify_discord',
    label: 'Discord Notification',
    category: 'notification',
    description: 'Send a message to a Discord channel via webhook.',
    icon: '💬',
    defaultConfig: { webhook_url: '', message: 'Encoding complete: {{.SOURCE_NAME}}' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'notify_teams',
    label: 'Teams Notification',
    category: 'notification',
    description: 'Send an adaptive card to a Microsoft Teams channel.',
    icon: '📣',
    defaultConfig: { webhook_url: '' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'notify_slack',
    label: 'Slack Notification',
    category: 'notification',
    description: 'Send a message to a Slack channel.',
    icon: '💭',
    defaultConfig: { webhook_url: '', channel: '#encoding' },
    inputs: 1,
    outputs: 1,
  },

  // ── Templates ──────────────────────────────────────────────────────────────
  {
    type: 'template_run',
    label: 'Run Template',
    category: 'template',
    description: 'Execute a saved encode/batch template.',
    icon: '📜',
    defaultConfig: { template_id: '' },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'template_frameserver',
    label: 'Frameserver Template',
    category: 'template',
    description: 'Apply an AviSynth or VapourSynth frameserver template.',
    icon: '🖥',
    defaultConfig: { template_id: '' },
    inputs: 1,
    outputs: 1,
  },

  // ── Flow Control ───────────────────────────────────────────────────────────
  {
    type: 'flow_chunk_split',
    label: 'Chunk Split',
    category: 'flow',
    description: 'Split the job into parallel encode chunks.',
    icon: '✂️',
    defaultConfig: { chunk_size_frames: 1000, overlap_frames: 0 },
    inputs: 1,
    outputs: 1,
  },
  {
    type: 'flow_concat',
    label: 'Merge / Concat',
    category: 'flow',
    description: 'Merge multiple chunk outputs back into a single file.',
    icon: '🔗',
    defaultConfig: { strategy: 'concat' },
    inputs: 4,
    outputs: 1,
  },
  {
    type: 'flow_fail',
    label: 'Fail Flow',
    category: 'flow',
    description: 'Immediately fail the flow with a custom error message.',
    icon: '🛑',
    defaultConfig: { error_message: 'Flow failed' },
    inputs: 1,
    outputs: 0,
  },
  {
    type: 'flow_delay',
    label: 'Delay',
    category: 'flow',
    description: 'Pause execution for a configurable number of seconds.',
    icon: '⏱',
    defaultConfig: { seconds: 5 },
    inputs: 1,
    outputs: 1,
  },
]

// Lookup map: type → NodeTemplate
export const NODE_REGISTRY_MAP: Map<string, NodeTemplate> = new Map(
  NODE_REGISTRY.map(t => [t.type, t])
)

// Group by category
export const NODE_BY_CATEGORY: Map<NodeCategory, NodeTemplate[]> = new Map()
for (const tpl of NODE_REGISTRY) {
  const list = NODE_BY_CATEGORY.get(tpl.category) ?? []
  list.push(tpl)
  NODE_BY_CATEGORY.set(tpl.category, list)
}

export const CATEGORY_LABELS: Record<NodeCategory, string> = {
  input: 'Input',
  encoding: 'Encoding',
  analysis: 'Analysis',
  condition: 'Conditions',
  audio: 'Audio',
  subtitle: 'Subtitles',
  output: 'Output',
  notification: 'Notifications',
  template: 'Templates',
  flow: 'Flow Control',
}

export const CATEGORY_COLORS: Record<NodeCategory, string> = {
  input: '#8b5cf6',
  encoding: '#14b8a6',
  analysis: '#3b82f6',
  condition: '#f59e0b',
  audio: '#22c55e',
  subtitle: '#a855f7',
  output: '#06b6d4',
  notification: '#ec4899',
  template: '#f97316',
  flow: '#6b7280',
}

export const CATEGORY_ORDER: NodeCategory[] = [
  'input',
  'encoding',
  'analysis',
  'condition',
  'audio',
  'subtitle',
  'output',
  'notification',
  'template',
  'flow',
]
